### ISSUE TITLE
How about setting default local port, remote port and ssh-server

### ISSUE THREAD

**Issue by yoheikikuta** [takahi-i/pfm#14]
### Description

I think it's better for us not to care about port numbers.
So how about setting default local & remote port numbers as simple incrementing numbers even across different remote servers.

Also, how about setting default ssh-server as localhost; almost all of the case for analysis in a remote server, we use localhost.

**Comment by takahi-i** [comment]
Thanks!

**Comment by takahi-i** [comment]
This is a great idea to help users. I will implement immediately!

**Comment by yoheikikuta** [comment]
I'm sure we can close this issue since it was implemented.

**Comment by takahi-i** [comment]
Thanks @yoheikikuta 👍
