### ISSUE TITLE
Shall we use dynamic port as default port number?

### ISSUE THREAD

**Issue by yoheikikuta** [takahi-i/pfm#15]
### Description

(This is a discussion)
Starting port number is 49152 and increment it.
https://en.wikipedia.org/wiki/List_of_TCP_and_UDP_port_numbers

**Comment by takahi-i** [comment]
👀

**Comment by takahi-i** [comment]
Thank you for giving great idea @yoheikikuta! sending pull request highly appreciate it.

**Comment by yoheikikuta** [comment]
Sent a PR: https://github.com/takahi-i/pfm/pull/17
Just changed the base and max_inferring numbers.

**Comment by takahi-i** [comment]
Fixed with #17 🎉
