### ISSUE TITLE
What do you say to adding 'connect' command

### ISSUE THREAD

**Issue by yoheikikuta** [takahi-i/pfm#18]
### Description

Now we need to execute `ssh 'pfm param [name]'` for ssh connections; I think it's not intuitive.
How about adding 'connect' command for ssh connection like `pfm connect [name]` ?

### What I Did

Simple implementation: https://github.com/yoheikikuta/pfm/blob/add-connect-command/pf_manager/pf_command/connect.py

**Comment by takahi-i** [comment]
> Now we need to execute ssh 'pfm param [name]' for ssh connections; I think it's not intuitive.

I see that you think `param` is not intuitive. `connect` is good name to run ssh command internally as your ConnectCommand implementation.

My one concern wrapping ssh command in `pfm` is that supporting misc ssh command line [options](http://linuxcommand.org/lc3_man_pages/ssh1.html) including not related to port forwarding tough.

Another concern is security, to be honest I am not sure whether wrapping ssh command is safe enough.

But I also understand wrapping ssh is valuable for data scientists for handy use. I think adding `connect` subcommand based on your implementation, and not removing `param` is better choice for now.

**Comment by takahi-i** [comment]
Supporting `--other-options ` to support misc ssh command line options in `pfm connect` could be a good idea.

**Comment by yoheikikuta** [comment]
I understood your points.
As you said, we should think deeper whether we need to add 'connect' command or not.
I'll consider the necessity and security.

**Comment by yoheikikuta** [comment]
Sent a PR: https://github.com/takahi-i/pfm/pull/34

**Comment by yoheikikuta** [comment]
I'm sure we can close this issue since this function is implemented.
